### ISSUE TITLE
JSON Date Format Error

### ISSUE THREAD

**Issue by zachduda** [astei/SuperbVote#100]
On startup, when there is a queued vote, the plugin throws an error and disables claiming that the timestamp is not formatted correctly on startup.

Minecraft Version: PaperSpigot (Build 44) 1.16.2
Using Java 11 (this may be the cause)
SB Version: v0.5.4
 
[Stacktrace Error](https://pastebin.com/raw/ruJncW3N)

How to reproduce:
1.  Vote with queuing enabled while not on the server.
2. Stop the server.
3. Start the server back up.

**Comment by irritatingness** [comment]
Just updated to Java 11 from 8, can confirm it seems to be a java version issue.

**Comment by astei** [comment]
This is... irritating. I'll take a look into this once I have time.

**Comment by astei** [comment]
On a side note, this is the first time I've gotten information on this problem that will let me solve it.

**Comment by irritatingness** [comment]
To give some more context, seems to be a Gson parsing issue.

Here's a pastebin of the error in my logs: https://pastebin.com/WbgMiQhw
