### ISSUE TITLE
Can this get updated for 1.16?

### ISSUE THREAD

**Issue by Towerism** [astei/SuperbVote#105]
Plugin does not load on 1.16

**Comment by astei** [comment]
You're going to have to give me a lot more detail than "plugin doesn't load on 1.16". Do you have some logs to share? What's your config?

**Comment by Towerism** [comment]
Welp, I was putting this off because I had taken a break from upgrading to 1.16. But I just upgraded today, and this plugin didn't give me any issues. So I'm going to close this.
