### ISSUE TITLE
Update to java 11

### ISSUE THREAD

**Issue by tommasobenatti** [astei/SuperbVote#110]
Please update the plugin to java 11

**Comment by NotAShelf** [comment]
with paper upgrading to java 11 starting from 1.17, I too think that this is necessary!

please update it as soon as possible, as it's the most extensive voting plugin to ever exist :)

**Comment by astei** [comment]
Duplicate of #100. Stop telling me that Paper is moving to Java 11, I was there when the decision was made.

**Comment by astei** [comment]
I will fix it when I have time. I no longer actively use SuperbVote so the time I spend on it is pretty limited.

**Comment by tommasobenatti** [comment]
K, thanks for the update
