### ISSUE TITLE
 Process-fake-votes doesn't work

### ISSUE THREAD

**Issue by TheoRetisch1** [astei/SuperbVote#71]
I set "process-fake-votes" to false. Nevertheless the rewards are triggered for all votes. This also applies to votes that do not represent a player of the server or a valid minecraft name. The change of the "process-fake-votes" option seems to have no effect at all. 

SuperbVote: 0.5.4
Paper 1.13.2 - 624
NuVotifier 2.5.2

**Comment by astei** [comment]
The term "fake vote" wasn't really well-defined, which is my fault.

A "fake vote", for SuperbVote's purposes is a vote issued using the `/sv fakevote` command. This is a command that assists in configuring the listener correctly.

Therefore, if `process-fake-votes` is `true`, then votes generated by the `/sv fakevote` command process rewards as usual but do not add a vote to the database.

Closing this issue.
