### ISSUE TITLE
Cumulative votes not working?

### ISSUE THREAD

**Issue by ichbinashh** [astei/SuperbVote#73]
Hi, I have tried to set it up so that players get x amount per vote, then every 24 votes they get a bonus amount. I'll attach my config in case I've done something wrong, but as far as I can see it should be working (it's not).

https://hastebin.com/yusinubega.pl

Thank you

**Comment by astei** [comment]
Please use a different pastebin, hastebin.com is totally inaccessible to me.

**Comment by ichbinashh** [comment]
https://pastebin.com/ZJkR7mcF

Apologies for that.

**Comment by astei** [comment]
https://github.com/astei/SuperbVote/wiki/Configuration#rewards

> **Order is important; the first condition that is met will be used**, unless you are using cascading.

Move your default reward to be the last one in the list. Then it should work.
