### ISSUE TITLE
Votes are not being rewarded

### ISSUE THREAD

**Issue by SrBedrock** [astei/SuperbVote#75]
Hey Astei,
After switching hosts and upgrading to version1.14.4, the plugin only registers the votes in queued_votes.json, do not announce votes or deliver rewards.
Could you help me figure out what I did wrong?

Server version: git-Paper-146 (MC: 1.14.4)

SuperBVote config.yml https://pastebin.com/DkfvMyaK
SuperBVote Version: 0.5.4

NuVotifier config.yml https://pastebin.com/WgFsffnT
NuVotifier Version: 2.5.3

**Comment by astei** [comment]
Your `config.yml` does not validate. Please use a tool like http://yaml-online-parser.appspot.com/ to find the errors in your `config.yml` and fix them.

**Comment by SrBedrock** [comment]
Is it still wrong?
https://pastebin.com/4bCnQ0jT

**Comment by astei** [comment]
Try applying it and see for yourself. It does validate, so SuperbVote should load it successfully.

**Comment by SrBedrock** [comment]
Do you know if after changing the server host I have to do something?
it looks like Votifier is ok..
https://imgur.com/ysGjLkj

**Comment by astei** [comment]
As long as the MySQL setup is updated, `/superbvote` works, and your test vote can be received and processed by SuperbVote, you should be good.

**Comment by SrBedrock** [comment]
I find a erro in the console:
https://pastebin.com/F74qyx3k
I don't think it has anything to do with my problem, but anyway I'm reporting.
The error may be with my Votifier since it is not reporting votes on the console.
