### ISSUE TITLE
Placeholder api for top voter misses the first voter

### ISSUE THREAD

**Issue by JHarris12345** [astei/SuperbVote#88]
Look at this screenshot:
![image](https://user-images.githubusercontent.com/46936647/77833630-f02ee800-7136-11ea-8e0f-0411231e09f5.png)

See how the top voter on the left is different to the one the hologram show? It misses number 1. The placeholder i used was:

/hd setline votetop 3 &61. &e%superbvote_top_voter_name_1% &a%superbvote_top_voter_votes_1%

**Comment by astei** [comment]
I do not maintain anything related to PlaceholderAPI, so you're reporting this in the wrong place.

From my brief glance of the code, it looks like you ought to count from zero instead of one.

**Comment by JHarris12345** [comment]
Counting from 0 didnt fix it
