### ISSUE TITLE
Problem!

### ISSUE THREAD

**Issue by StormyBluey** [astei/SuperbVote#93]
Hello so i have a problem with my server and the plugin as i have it as 
`
  # Whether or not to treat fake votes as real votes
  process-fake-votes: true

# Rewards. This is the main section you will need to edit. Ordering is important.
rewards:
  # Example of matchers. See https://github.com/minecrafter/SuperbVote/wiki/Configuration#if for a full list of available
  # matchers.
  - if:
      permission: superbvote.test
      chance-percentage: 20
      service: SpecialService
    commands:
    - eco give %player% 50
    - cc give %player% physical Basic
    player-message: "&aThanks for meeting nearly impossible conditions, you have been rewarded with a BASIC KEY and $50."
    broadcast-message: "&a%player% got really lucky and was rewarded with BASIC KEY!!
  # A default reward is required. Default rewards are defined by using default: true as a matcher. No other matchers can
  # be used with this matcher and only one such reward can be the default reward.
  - if:
      default: true
    commands:
    - eco give %player% 50
    player-message: "&aThanks for voting for us on %service%, you have been rewarded with $50."
    broadcast-message: "&a%player% has voted for us on %service% and was rewarded with $50!"

# Whether or not players need to be online to vote. If set, offline player votes are queued for when the player next logs in.
require-online: true
`
But in chat it gives the player $1000 no matter what site they are using. Here is config and screen shot in game
![HELP1](https://user-images.githubusercontent.com/16232625/82763961-56ec1d00-9dd9-11ea-9fef-44acfce724ee.PNG)
![help2](https://user-images.githubusercontent.com/16232625/82763962-5c496780-9dd9-11ea-9018-7b0d40f05da0.PNG)

**Comment by astei** [comment]
You probably forgot to reload the configuration.

**Comment by StormyBluey** [comment]
Actually i have already reloaded the plugin. I did it again here as well nothing is working with the configuration from the plugin to the voting system, Its only 1000$ when changed.

![Koil909090](https://user-images.githubusercontent.com/16232625/82781628-4a42e580-9e28-11ea-97ad-f6eb55297841.PNG)
