### ISSUE TITLE
Group matcher is based on display name

### ISSUE THREAD

**Issue by Towerism** [astei/SuperbVote#97]
I'm using luckperms, and I gave a bunch of my groups display names which broke all of my SuperbVote matchers until I changed all of the matchers to use the display names.

The group matcher should be based on the group name so that the group display name can be used freely without breaking the matcher.

**Comment by astei** [comment]
This is going to be an artifact of how LuckPerms interacts with Vault (or vice versa). I don't have any control over this. SuperbVote uses Vault to look up group names for each player, and whatever LuckPerms provides to Vault is what SuperbVote uses for its lookup.
