### ISSUE TITLE
/vote command not giving any messages even with a wiped config file.

### ISSUE THREAD

**Issue by ovwa** [astei/SuperbVote#99]
Everytime I do /vote it doesn't send a message nor an error to the console. I've tried refreshing the SuperbVote folder so its new generated files it still doesn't send anything? I'm using the latest version.

**Comment by astei** [comment]
The /vote command is disabled by default. Please enable it. This is documented in the [documentation](https://github.com/astei/SuperbVote/wiki/Configuration).
